### ISSUE TITLE
Establish initial provider capabilities

### ISSUE THREAD

**Issue by mansam** [konveyor-ecosystem/k8s-provider#4]
At its most basic, the provider needs to have a capability that can evaluate a Rego policy that it is given against the resources pulled from the cluster, and then transmogrify the policy engine's results into provider incidents. So far the prototype has an implementation of this that requires the input policies to return results in a specific "incident" format so that the provider can interpret them. For example:

```rego
      package policy
      import data.lib.konveyor
      import future.keywords

      incidents[msg] {
      	some item in data.lib.konveyor.deployments
        item.spec.replicas == 1
      	msg := {
            "apiVersion": item.apiVersion,
      		"namespace": item.metadata.namespace,
      		"kind": item.kind,
      		"name": item.metadata.name,
      	}
      }
```

This sort of freeform rules writing is very powerful and opens up all the capabilities of OPA at the expense of some boilerplate to get the result into the right format. I think we could also introduce a second capability that just takes a single Rego expression and a collection of resources to operate on (see #2), and then generates the necessary boilerplate. For example:

```yaml
ruleID: replica-count-simple
effort: 1
category: optional
message: "Low replica count"
when:
  rego.expr:
    collection: deployments
    expression: item.spec.replicas == 1
```
